### ISSUE TITLE
Left menu favorites and recently visited items are not changed by CSS

### ISSUE THREAD

**Issue by teun95** [denyskorolkov/logseq-immersion-theme#4]
![image](https://user-images.githubusercontent.com/37039643/193309377-c592853c-cee5-4cda-92b2-8b7482d94a52.png)

This occurs no matter whether the theme was installed as plugin or through `logseq/config.edn` and `custom.css`.

Logseq version 0.8.8

**Comment by denyskorolkov** [comment]
Fixed
